---
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: 'https://github.com/jmhbnz/talks.git'
    deployment.kubernetes.io/revision: '1'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"guestbook:latest","namespace":"guestbook"},"fieldPath":"spec.template.spec.containers[?(@.name==\"guestbook\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  name: guestbook
  namespace: guestbook
  labels:
    app.kubernetes.io/component: guestbook
    app.kubernetes.io/instance: guestbook
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/part-of: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: guestbook
        deployment: guestbook
    spec:
      containers:
        - name: guestbook
          image: image-registry.openshift-image-registry.svc:5000/guestbook/guestbook:latest
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
