- name: "Configure demo infra"
  hosts: all
  gather_facts: false
  vars:
    ansible_host_key_checking: false

  tasks:

    - name: "Wait for ssh connection"
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 600

    - name: "Register machine via subscription manager"
      community.general.redhat_subscription:
        state: present
        username: rh-ee-jablair
        password: "{{ lookup('env', 'TF_VAR_subscription_pw') }}"
        auto_attach: false

    - name: "Ensure manage repos set correctly"
      ansible.builtin.shell: |
        sudo sed -i 's/manage_repos = 0/manage_repos = 1/g' /etc/rhsm/rhsm.conf
